# Task_6 (Numpy)


# Q.1.Arrays

In [1]:
import numpy

def arrays(arr):
    A = numpy.array(arr,float)
    return A[::-1]
arr = input().strip().split(' ')
result = arrays(arr)
print(result)

1 2 3 4 -8 -10
[-10.  -8.   4.   3.   2.   1.]


## Q.2.Shape and Reshape

In [2]:
import numpy
s=list(map(int, input().strip().split(" ")))
print(numpy.reshape(s,(3,3)))


1 2 3 4 5 6 7 8 9
[[1 2 3]
 [4 5 6]
 [7 8 9]]


## Q.3. Transpose and Flatten



In [3]:
import numpy
l=[]
n,m=input().split(" ")
s=numpy.array([input().split(" ") for _ in range(int(n))],int)
print(numpy.transpose(s))
print(s.flatten())


        



2 2
1 2
3 4
[[1 3]
 [2 4]]
[1 2 3 4]


## Q.4.Concatenate

In [4]:
import numpy
n,m,p=input().split(" ")
a=numpy.array([input().split(" ") for _ in range(int(n))],int)
b=numpy.array([input().split(" ") for _ in range(int(m))],int)
print(numpy.concatenate((a, b), axis = 0)   )



4 3 2
1 2
1 2
1 2
1 2
3 4
3 4
3 4
[[1 2]
 [1 2]
 [1 2]
 [1 2]
 [3 4]
 [3 4]
 [3 4]]


## Q.5.Zeros and Ones



In [5]:
import numpy
n=input().split(" ") 
k=numpy.array(n,int) 
arr1=numpy.zeros(((k)),dtype = numpy.int)
print(arr1)
arr2=numpy.ones(((k)),dtype = numpy.int)
print(arr2)

3 3 3
[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]
[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]


## Q.6.Eye and Identity



In [6]:
import numpy
n=input().split(" ") 
k=numpy.array(n,int) 
numpy.set_printoptions(legacy='1.13')
print(numpy.eye(k[0],k[1],k = 0))



3 3
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


## Q.7.Array Mathematics



In [7]:
import numpy
n,m=map(int, input().split())
a, b = (numpy.array([input().split() for _ in range(n)], dtype=int) for _ in range(2))
print(numpy.add(a,b))
print(numpy.subtract(a,b))
print(numpy.multiply(a,b))
print(numpy.floor_divide(a,b))
print(numpy.mod(a,b,dtype=int))
print(numpy.power(a,b))



1 4
1 2 3 4
5 6 7 8
[[ 6  8 10 12]]
[[-4 -4 -4 -4]]
[[ 5 12 21 32]]
[[0 0 0 0]]
[[1 2 3 4]]
[[    1    64  2187 65536]]


## Q.8.Floor, Ceil and Rint



In [8]:
import numpy

my_array = numpy.array(input().split(" "),float)
numpy.set_printoptions(legacy='1.13')

print(numpy.floor(my_array))
print(numpy.ceil(my_array))
print(numpy.rint(my_array))


1.1 2.2 3.3 4.4 5.5 6.6 7.7 8.8 9.9
[ 1.  2.  3.  4.  5.  6.  7.  8.  9.]
[  2.   3.   4.   5.   6.   7.   8.   9.  10.]
[  1.   2.   3.   4.   6.   7.   8.   9.  10.]


## Q.9.Sum and Prod



In [9]:
import numpy
n,m=map(int, input().split())
a= (numpy.array([input().split() for _ in range(n)], dtype=int))
print(numpy.prod(numpy.sum(a, axis=0), axis=0))




2 2
1 2
3 4
24


## Q.10.Min and Max



In [10]:
import numpy
n,m=map(int, input().split())
a=numpy.array([list(map(int,(input().split()))) for i in range(int(n))])
print(numpy.max(numpy.min(a,axis=1),axis=None))


4 2
2 5
3 7
1 3
4 0
3


## Q.11.Mean, Var, and Std



In [11]:
import numpy
n,m=map(int, input().split())
a=numpy.array([list(map(int,(input().split()))) for i in range(int(n))])
print(numpy.mean(a,axis=1))
print(numpy.var(a,axis=0))
print(round(numpy.std(a),11))





2 2
1 2
3 4
[ 1.5  3.5]
[ 1.  1.]
1.11803398875


# Q.12.Dot and Cross




In [12]:
import numpy
n=int(input())
a=numpy.array([list(map(int,(input().split()))) for i in range(int(n))])
b=numpy.array([list(map(int,(input().split()))) for i in range(int(n))])
print(numpy.dot(a,b))




2
1 2
3 4
1 2
3 4
[[ 7 10]
 [15 22]]


# Q.13.Polinomials

In [14]:
import numpy
poly = [float(x) for x in input().split()]
x = float(input())
print(numpy.polyval(poly,x))

1.1 2 3
0
3.0


# Q.14.Inner and Outer



In [16]:
import numpy
a=numpy.array([list(map(int,(input().split())))])
b=numpy.array([list(map(int,(input().split())))])
print(numpy.inner(a,b)[0][0])
print(numpy.outer(a,b))

0 1
2 3
3
[[0 0]
 [2 3]]


# Q.15.Linear Algebra



In [15]:
import numpy
n=float(input())
a=numpy.array([list(map(float,(input().split()))) for i in range(int(n))])
print(round(numpy.linalg.det(a),2))



2
1.1 1.1
1.1 1.1
0.0
